sudo: required

services:
  - docker

before_install:
  - curl -L https://github.com/docker/compose/releases/download/1.16.1/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
  - chmod +x /usr/local/bin/docker-compose

script:
  - XDEBUG=1 docker-compose build
  - docker-compose run --rm app php -i