version: '2'
services:
    redis:
        image: redis
    db:
        image: mariadb
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        ports:
            - 3410:3306
        environment:
            - "MYSQL_RANDOM_ROOT_PASSWORD=1"
            - "MYSQL_DATABASE=${DB_NAME}"
            - "MYSQL_USER=${DB_USER}"
            - "MYSQL_PASSWORD=${DB_PASSWORD}"
        logging:
            driver: "json-file"
            options:
              max-size: "10m"
              max-file: "50"
    app:
        build:
            context: ./docker/app
            args:
                - XDEBUG
        working_dir: /var/www/app
        links:
            - redis
            - db
        volumes:
            - ./:/var/www/app:rw
        logging:
            driver: "json-file"
            options:
              max-size: "10m"
              max-file: "50"
        environment:
            - "REDIS_HOST=redis"
            - "DB_NAME"
            - "DB_USER"
            - "DB_PASSWORD"
    web:
        build: ./docker/web
        restart: unless-stopped
        ports:
            - 8080:80
        links:
            - app
        volumes_from:
            - app
        logging:
            driver: "json-file"
            options:
              max-size: "10m"
              max-file: "50"