version: '2.4'
services:
    db:
        ports:
            - 127.0.0.1:13306:3306

    app:
        volumes:
            - ./docker/app/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro

    web:
        ports:
            - $LISTEN_WEB:80